### ISSUE TITLE
fix  to server side page

### ISSUE THREAD

**Issue by Erriccc** [tippi-fifestarr/dd#1]
'use client';

// import { useState } from "react";
import Person from "./person";
import Image from "next/image";
import React, {useState, useEffect} from 'react';

export default  function Cards() {
  const [someData,setSomeData] = useState(undefined);
  const [moreData,setMoreData] = useState(undefined);

  const defineAsyncFunctionsHere = async () => {
    return
  }

  useEffect(() => {
  
      const performOtherAsyncCalls = async () => {
        const imagePath = "http://image.tmdb.org/t/p/original";
              const data = await fetch(
          `https://api.themoviedb.org/3/person/popular?api_key=${process.env.TMDB_API_KEY}`
        );
        const res = await data.json();
        newRes = res.results.sort((a, b) => 0.5 - Math.random());
        //   console.log(res);
        setMoreData(newRes[0])

        setSomeData(newRes)

        return
      }

      someData !== undefined && performOtherAsyncCalls()
          return

    },[someData,moreData]);
  //   const config = await fetch(
  //     `https://api.themoviedb.org/3/configuration?api_key=${process.env.TMDB_API_KEY}`
  //   );

  //   const configo = await config.json();
  //   console.log(configo.images.base_url);
  //   const profSizes = configo.images.profile_sizes;
  //   console.log(profSizes[1]);
  //   const imagePath = `${configo.images.base_url}w185`;
  

  //   const [selectedCard, setSelectedCard] = useState("");
  // state for which card was clicked

  // update the hero image to show clicked
  return (
    // map through the res and return 25 names
    <div className="flex flex-col">
      {/* display details of selected card, larger image, person name, knownfor */}
      <div className="relative flex justify-center border-2 border-slate-400 rounded-xl p-2 gap-20 my-1 mx-5">
       {someData !== undefined && moreData !== undefined &&  <Image
          src={imagePath + moreData.profile_path}
          alt={`image of ${moreData.name}`}
          className="object-contain rounded-md"
          height={128}
          width={128}
        />}

        <div className="flex relative gap-2 border-red-500 rounded-md p-1 bg-red-200">
          You've clicked on {someData[0]?.name}
        </div>
      </div>
      <div className="border-slate-200 border-2 rounded-lg px-5 mx-5">
        <div className="grid grid-cols-5">
          {someData?.map((person) => (
            <div className="m-1">
              <Person
                className="flex gap-2"
                name={person.name}
                known_for={
                  person.known_for[0].name
                    ? person.known_for[0].name
                    : person.known_for[0].title
                }
                profile_path={person.profile_path}
                imagePath={imagePath}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

**Comment by tippi-fifestarr** [comment]
@Erriccc well, i tried this, thank you!  i think i got the main idea here but now I'm doing something wrong in my conditional render.  Kinda tired will try again tomorrow or thursday.  

Just pushed the changes, if you get a chance to check it out let me know. 
My next step will be see if GPT can figure out what i did wrong haha
I think its something having a wrapping div and then conditionally rendering only that top detail component on the state of people fetched and card clicked

Thanks again dude

**Comment by tippi-fifestarr** [comment]
Migrating from _appdir to normal next 13 as I setup Thirdweb
